spring:
  application:
    name: bookstore

  datasource:
    url: jdbc:postgresql://postgres:5432/bookstore
    username: bookstore
    password: bookstore
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jooq:
    sql-dialect: POSTGRES

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
  file:
    name: logs/bookstore-app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: myapp-%d{yyyy-MM-dd}.%i.log
      max-history: 30